Document: argm
Title: Debian argm Manual
Author: <insert document author here>
Abstract: This manual describes what argm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/argm/argm.sgml.gz

Format: postscript
Files: /usr/share/doc/argm/argm.ps.gz

Format: text
Files: /usr/share/doc/argm/argm.text.gz

Format: HTML
Index: /usr/share/doc/argm/html/index.html
Files: /usr/share/doc/argm/html/*.html
